### PR TITLE
various small bugfixes and added features

### PR DESCRIPTION
**Pull request by christopherfujino**

### CODE REVIEW

**Review by ccpinotti — APPROVED** [review]
looks good

**Review by ccpinotti — APPROVED** [review]
looks good

**Review by ccpinotti — APPROVED** [review]
looks good

**Review by ccpinotti — APPROVED** [review]
looks good

**Review by ccpinotti — APPROVED** [review]
looks good

**Review by ccpinotti — APPROVED** [review]
looks good

**Comment by christopherfujino** [comment]
Thanks Chris, I guess it really looks good :P

**Pull request merged**
